.TH libft-gc-misc 3 "MARCH 2024" "libft man-pages"
.SH NAME
ft_getvm, ft_sweep, ft_clean, ft_exit, ft_return \- misc gc functions
.SH LIBRARY
libft (\fI-lft\fR)
.SH SYNOPSIS
.nf
\fBt_vm    *ft_getvm(void);\fR
\fBvoid    ft_sweep(t_vm \fI*vm\fB);\fR
\fBvoid    ft_clean(void);\fR
\fBvoid    ft_exit(int32_t \fIestat\fB);\fR
\fBint32_t ft_return(int32_t \fIrval\fB);\fR
.nf
.SH DESCRIPTION
.SS ft_getvm()
\fBft_getvm\fR() fetches the vm struct (see \fBlibft-data\fR(7))
.SS ft_sweep()
\fBft_sweep\fR() frees all unmarked objects
.SS ft_clean()
\fBft_clean\fR() frees all unused objects
.SS ft_exit()
\fBft_exit\fR() frees all objects and calls \fBexit\fR(3) with \fIestat\fR
.SS ft_return()
\fBft_return\fR() frees all objects
.SH RETURN VALUE
\fBft_getvm\fR() returns a pointer to the vm struct
.P
\fBft_return\fR() returns \fIrval\fR
.SH SEE ALSO
\fBlibft-gc\fR(7)
