.TH libft 7 "MARCH 2024" "libft man-pages"
.SH NAME
libft \- overview of the libft library
.SH MODULES
.SS gc
Functions related to the libft garbage collector (see \fBlibft-gc\fR(7))
.SS gnl
get_next_line (see \fBlibft-gnl\fR(3))
.SS is
Functions related to checking values (see \fBlibft-is\fR(3))
.SS lst
Functions related to t_list lists (see \fBlibft-lst\fR(3))
.SS mem
Functions related to memory manipulation (see \fBlibft-mem\fR(3))
.SS nbr
Functions related to numbers (see \fBlibft-nbr\fR(3))
.SS printf
ft_printf (see \fBft_printf\fR(3))
.SS put
Functions related to printing output (see \fBlibft-put\fR(3))
.SS str
Functions related to strings (see \fBlibft-str\fR(3))
.SS to
Functions related to conversions (see \fBlibft-to\fR(3))
.SH SEE ALSO
\fBlibft-data\fR(7)
