.TH libft 7 "MARCH 2024" "libft man-pages"
.SH NAME
libft \- overview of the libft library
.SH MODULES
.SS gc
Functions related to the libft garbage collector (see \fB\libft-gc\fR(7))
.SS gnl
get_next_line (see \fB\libft-gnl\fR(3))
.SS is
Functions related to checking values (see \fB\libft-is\fR(7))
.SS lst
Functions related to t_list lists (see \fB\libft-lst\fR(7))
.SS mem
Functions related to memory manipulation (see \fB\libft-mem\fR(7))
.SS nbr
Functions related to numbers (see \fB\libft-nbr\fR(7))
.SS printf
ft_printf (see \fB\ft_printf\fR(3))
.SS put
Functions related to printing output (see \fB\libft-put\fR(7))
.SS str
Functions related to strings (see \fB\libft-str\fR(7))
.SS to
Functions related to conversions (see \fB\libft-to\fR(7))
.SH SEE ALSO
\fB\libft-data\fR(7)
